rebuild-srpms.sh
fedora-modularity/baseruntime-package-lists pull request #7
Opened 2017-06-03 01:11 UTC by ignatenkobrain

Effective way of rebuilding srpms located in current directory.

For usual fedora SRPMs, the speed on 8-core Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz
with Samsung MZ7LN512HCHP SSD (up to 540 MB/s, 97 KIOPS) is around 5-20 pkgs/s.

Signed-off-by: Igor Gnatenko <ignatenkobrain@fedoraproject.org>

2017-06-03 01:18 UTC, ignatenkobrain commented on rebuild-srpms.sh
> +  dist=$(rpm -qp --qf "%{release}\n" "$srpm" | grep -Po "\.fc\d+")
this is ugly, but I don't know any other way apart from extracting SPEC, trying to parse it with different dist tag and find difference which is (however) is unreliable

2017-06-05 01:10 UTC, sgallagher commented
What does this do that https://github.com/sgallagher/baseruntime-package-lists/blob/master/recreate_srpm.sh does not? And why not enhance that file instead of creating a new approach?

2017-06-05 05:31 UTC, ignatenkobrain commented
Why not to enhance it -- it doesn't download anything (which is useful when I want to rebuild 60 GiB of SRPMs).. this means they have different usage.

Why to create new script -- I needed to rebuild 60 GiB of SRPMs in a quick way..

We should make first script to do something else like downloading all SRPMs from tag (see another PR) and call this script to regenerate all of them.

2017-06-05 13:36 UTC, sgallagher requested changes
@ignatenkobrain My main point was that a lot of the code here was duplicated. I'd rather not maintain two ways of doing things; if you have a more efficient way of solving both problems, please put them into the same PR (and have them call the same functions) so we don't end up having them get out of sync.

2017-06-06 19:08 UTC, sgallagher commented
@ignatenkobrain Another point: the reason that my scripts perform this inside a mock chroot is to minimize the possibility of the host environment changing the output. (For example, if a package checks the version of an interpreter on the system and encodes that into its requirements).

2017-06-06 21:07 UTC, ignatenkobrain commented
@sgallagher recreate_srpm.sh doesn't do anything in mock chroot..

2017-06-06 23:46 UTC, sgallagher commented
@ignatenkobrain It does when paired with `mock_wrapper.sh`

2017-07-10 13:49 UTC, merged